### ISSUE TITLE
Select with a complex item

### ISSUE THREAD

**Issue by Fenntasy** [NoRedInk/list-selection#1]
For the moment, the selection is only doable with `select : a -> Selection a -> Selection a` which is great when `a` is a simple type but will be harder if it is a record (or a complex data structure, like a `JsonApi.Document`).

Could it be appropriate to also have something like `selectCustom : (a -> Bool) -> Selection a -> Selection a`?

**Comment by BrianHicks** [comment]
Hello! It certainly could be appropriate. Is this something you need right now? Could you add concrete details about your use case so we can be sure to solve the right problem?

**Comment by Fenntasy** [comment]
Hello,

I could do some refactoring in my work at the moment with this little change but "right now" seems too demanding ;)

> Could you add concrete details about your use case so we can be sure to solve the right problem?

Of course!
I have a sequence of dropdowns where I select an item, call an API to get the list of associated items to populate the next dropdown (3 times but I don't think it's relevant).

Each of those API calls returns a JSON formatted with [JSON API](http://jsonapi.org) and I'm using [noahzgordon/elm-jsonapi](http://package.elm-lang.org/packages/noahzgordon/elm-jsonapi/latest) to manage the results.

For the moment, I'm using a `selectedValue : Maybe JsonApi.Resource` and a `values : Maybe (List JsonApi.Resource)`. I then construct the dropdown with the `values`, showing a disabled select if `values == Nothing` and a list of options otherwise with a first blank option when nothing has been selected by the user. But in order to compare easily the selection, I use the resources ids to avoid comparing big objets (they're UUIDs and a deep comparison would be too much).

```elm
    -- ...
    select
        [ class "form-control"
        , on "change" (Decoder.map SelectValue targetValue)
        ]
        (option [ selected (selectedValue == Nothing) ] []
             :: List.map (viewOption selectedValue) values
        )
     -- ...

viewOption : Maybe JsonApi.Resource -> JsonApi.Resource -> Html Msg
viewOption currentSelection current =
    let
        isSelected =
            (JsonApi.Resources.id current)
                == (currentSelection
                        |> Maybe.map JsonApi.Resources.id
                        |> Maybe.withDefault ""
                   )
    in
        option
            [ selected isSelected
            , value (JsonApi.Resources.id current)
            ]
            [ text <| extractNameFromJsonApiResource current ]
``` 


I think your lib is the right abstraction for my problem: a list of values that can have a selection.

**Comment by BrianHicks** [comment]
Yeah! I see what you mean. Several people have asked me about that but you're the first person to open an issue so you get a piece of cake: 🍰 

Anyway, thinking aloud! I like this signature:

```elm
selectBy : (a -> Bool) -> Selection a -> Selection a
```

But I'm concerned about these cases:

1. What happens if you have `fromList [1, 2, 3]` and you try `selectBy ((==) 4)`? I would assume the same thing that happens if you try to select something that doesn't exist (no-op.)
2. What happens if there are two items who are not unique, except for the field you're selecting on? What should `fromList ["aardvark", "armadillo"] |> selectBy (String.startsWith "a")` do?

Of the two, I'm more concerned about unexpected behavior occurring in the second case. Do you have any thoughts?

**Comment by BrianHicks** [comment]
Also, I'm curious how you're measuring deep comparisons being too much. Are you benchmarking it? Is it causing noticeable lag for your users?

**Comment by Fenntasy** [comment]
> Also, I'm curious how you're measuring deep comparisons being too much. Are you benchmarking it? Is it causing noticeable lag for your users?

Well... No I must admit I have no real reason to say that ^^'. But to be fair, there is also one case where I need to find one element where I only have the id at my disposal (because of relationships and the way JSON API is structured). So even if there si no performance cost, the need is still there ;)

> What happens if you have `fromList [1, 2, 3]` and you try `selectBy ((==) 4)`? I would assume the same thing that happens if you try to select something that doesn't exist (no-op.)

I see no reason to have a different behaviour than with `select`

```elm
fromList ["Burrito", "Chicken Wrap", "Taco Salad"]
    |> select "Doner Kebab"
    |> selected --> Nothing

fromList ["Burrito", "Chicken Wrap", "Taco Salad"]
    |> selectBy ((==) "Doner Kebab")
    |> selected --> Nothing
```

> What happens if there are two items who are not unique, except for the field you're selecting on? What should `fromList ["aardvark", "armadillo"] |> selectBy (String.startsWith "a")` do?

I would think the simpler way is to select the first that pass the test. As for [SelectList.select](http://package.elm-lang.org/packages/rtfeldman/selectlist/1.0.0/SelectList#select). Is it something weird?

What are the other options? Not selecting anything if there is more than one result sounds weirder.

By the way, thanks, I didn't know the aardvark :)
