### ISSUE TITLE
What about updating the list?

### ISSUE THREAD

**Issue by ibizaman** [NoRedInk/list-selection#3]
The use case is that there's a `Selection a` where the list of item needs to be updated. It would be great to have a function to handle the potential case where the previously selected item does not appear anymore in the new list.

As a first draft, the function could be:
```elm
transferSelection : Selection a -> Selection a -> ( Selection a, Bool )
transferSelection old new =
    case Sel.selected old of
        Nothing ->
            ( new |> Sel.deselect, True )

        Just selected ->
            let
                newSelected =
                    new |> Sel.select selected
            in
                case Sel.selected newSelected of
                    Just _ ->
                        ( newSelected, True )

                    Nothing ->
                        ( newSelected, False )
```

The `Bool` in the returned tuple indicates is the previously selected item is present in the new list. I'm using this `Bool` to indicate to show an error if the previously selected item is not in the new list.

Tangential to this, it would be great to have a `isSelected` function too. This would simplify the above implementation too:
```elm
transferSelection : Selection a -> Selection a -> ( Selection a, Bool )
transferSelection old new =
    case Sel.selected old of
        Nothing ->
            ( new |> Sel.deselect, True )

        Just selected ->
            let
                newSelected =
                    new |> Sel.select selected
            in
                ( newSelected, Sel.isSelected newSelected )
```

What are your thoughts about this?

**Comment by BrianHicks** [comment]
Hey! Sorry for the delay. I'm thinking about this now… and I'm not sure that I understand your use case well enough to say "yeah that makes sense" or "maybe we could try something else." Could you be more specific about your situation so we can design something that will work for you? 😄

**Comment by ibizaman** [comment]
Sorry I don't have context on this anymore 😅
